notifications:
  disabled: true
before_install:
  - gem install bundler
bundler_args: --without extra
rvm:
  - ree
  - 1.9.3
  - 2.0.0
env:
  - XML_PARSER=rexml
  - XML_PARSER=nokogiri
  - XML_PARSER=libxml
  # does not work yet
  # - XML_PARSER=ox
