notifications:
  disabled: true
bundler_args: --without extra
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  - XML_PARSER=rexml
  - XML_PARSER=nokogiri
  - XML_PARSER=libxml
  # does not work yet
  # - XML_PARSER=ox
